### ISSUE TITLE
ConvertSetup800to990 issues?

### ISSUE THREAD

**Issue by gitl0ver** [sagamusix/JDTools#13]
Reporting here again, my apologies...but at least one of the issues I'm reporting is new, and the other I have explained in better detail/made the issue more clear. I'm running the latest public release on Windows 10, and I haven't been able to get JDTools to accurately convert JD-800 special setups to my JD-990 (running firmware revision 1.01, if this helps). My issues:

- The tones are erratically panned left and right, which shouldn't be possible since this is an 800 setup. I don't know where it's producing the nonexistent data from, since it even does this on initialized patches where the pan for all tones is set to 0.

- Entire pages of parameters in the Common and Effects section (General, EQ, Chorus, Delay, Reverb) are not initialized or overwritten. They remain the same as the patch they're overwriting. I have been made aware the raw .syx data cannot contain parameters for the effects section in these cases. However, if they could be assigned the same parameters as the factory JD-800 special set configuration, it would be very helpful and much appreciated. Digging through the repository, in the ConvertSetup800to990 function located in Convert800to990.cpp, from lines 264 on, it looks like there's a whole list of parameters here that aren't writing correctly unless they have been dummied out/are intended for something else entirely (not a programmer, apologies!). As previously mentioned, even EQ (which I'm assuming does exist in the .syx file since it's being referenced here) doesn't get written, and I'm assuming all the pre-defined parameters for common, chorus, reverb, delay, etc. are the JD-800 defaults/equivalents for this setup. These don't get written either. Screenshot of some of the aforementioned lines attached below.
![git](https://github.com/sagamusix/JDTools/assets/155190818/3f239909-0c21-4d4d-b043-71491e5e664e)
Hope I have not made any mistakes in my writings here...not ruling out the possibility that it is an incompatibility with my JD's firmware or something like that. As always, thanks for this awesome tool!

**Comment by sagamusix** [comment]
> The tones are erratically panned left and right, which shouldn't be possible since this is an 800 setup. I don't know where it's producing the nonexistent data from, since it even does this on initialized patches where the pan for all tones is set to 0.

JD-800 setups (just like JD-990 setups, where this information is part of the regular tone settings) have an individual pan settings for each note. This is not a bug, and it is a feature the JD-800 default setup makes use of. I'm not sure what you mean by your second sentence because patches and tones don't have any panning settings on the JD-800, only setup keys do, and generally the conversion of setups and patches is completely unrelated.

As for the second issue, I don't quite understand what the problem is, as you keep switching between patches/tones and setups, which are two distinct things. As mentioned before, there is no effect information on JD-800 setups, so the JD-990 setup effect information is pre-filled with default settings. Those defaults were taken from the standard JD-990 setup if I remember correctly, but I could be wrong. The SysEx dumps that JDTools create are always for a complete patch or setup. It is not possible that only parts of a setup or patch are overwritten, unless there is a data transmission issue.

**Comment by gitl0ver** [comment]
My apologies. I explained rather poorly, but from what you've suggested, I'll just chalk it up to a case of user error here, so the issue is resolved I suppose. Again, thanks for the awesome tool!
