### ISSUE TITLE
JD-08 conversion only partially working

### ISSUE THREAD

**Issue by aleks19841** [sagamusix/JDTools#7]
I just noticed the SVD file conversion only partially working.
First, the tools says source has been identified as JD-800 VST, not sure if just typo or wrong source autodetect.
Then all the patches start at I** and only first 64 patches I11-I88 are imported.
Same behaviour when converting and also when listing patches in the SVD

<img width="616" alt="Screenshot 2022-09-05 at 10 53 20" src="https://user-images.githubusercontent.com/112858482/188409676-b3990ee4-d9de-4b33-84c0-3bacb192b9da.png">

**Comment by sagamusix** [comment]
> First, the tools says source has been identified as JD-800 VST, not sure if just typo or wrong source autodetect.

This is just an internal limitation to keep the code simple. All three ZenCore formats (plugin BIN, SVZ and SD) will say so. Maybe I should reword it a bit.

It sounds like you are using an older version of the converter because both of those issues should already be fixed. Please download the latest version from https://github.com/sagamusix/JDTools/releases and give it another try.

**Comment by aleks19841** [comment]
Thanks for the quick reply.
Already running the latest v 0.13
I just tested default factory backup SVD and some 3rd party banks, same behaviour, only patches I11-I88 are listed and/or converted

**Comment by sagamusix** [comment]
Can you maybe attach the backup file to this issue to have a look at? Maybe there's something different about it due to a different firmware version compared to what I have seen before.

**Comment by aleks19841** [comment]
sure, here's the factory bank, JD-08 firmware v1.02, I also have some (paid) 3rd party banks, that I can't share publicly unfortunately...

[JD08Factory.svd.zip](https://github.com/sagamusix/JDTools/files/9488760/JD08Factory.svd.zip)

**Comment by sagamusix** [comment]
The `list` command indeed only lists the first 64 patches. This will be fixed in the next version. However, conversion works fine here: As the target formats only support 64 patches per bank, 4 output files are generated - one for each bank. The patch index that is shown during conversion is that of the target file (so you will see I11...I88 being repeated four times), but I will change it to show the patch index of the source file instead (so it will go from A11 to D88 for SVD files.)

**Comment by sagamusix** [comment]
Can you please give version 0.14 a try? Now available from https://github.com/sagamusix/JDTools/releases

**Comment by aleks19841** [comment]
0.14 lists the patches correctly for factory bank and for banks converted from BIN format.
So far so good.
However 3rd party banks only list the first 64 (factory) patches, nothing beyond that. I wonder if the 3rd party SVDs could be corrupted in some way, but they load just fine on JD-08.
I also  tried converting BIN to JD-08 format:
it works fine when converting one bank (64 patches) to SVD starting on C11 (keeping factory presets), but when I add another 64 patches from another BIN starting on D11, jdtools lists all the patches correctly from the SVD, but JD-08 throws an error on restore...

**Comment by sagamusix** [comment]
> However 3rd party banks only list the first 64 (factory) patches, nothing beyond that. I wonder if the 3rd party SVDs could be corrupted in some way, but they load just fine on JD-08.

Technically it is perfectly fine for a SVD file to contain less than 64 patches. Without being able to look at the file I cannot judge if that is the case, though. You could send one of those files to info @ (my github account name) . de privately and I will have a look.

> it works fine when converting one bank (64 patches) to SVD starting on C11 (keeping factory presets), but when I add another 64 patches from another BIN starting on D11, jdtools lists all the patches correctly from the SVD, but JD-08 throws an error on restore...

Please also send the source BIN file and the resulting SVD, just to be sure that we're on the same page. I don't have a JD-08 so I can only guess if the generated files are valid, but if I try the same here the output file looks fine to me.

**Comment by sagamusix** [comment]
Got the files, thank you. There was another stupid bug when converting from SVD to BIN or SVZ which should be gone in the next version, so instead of getting four banks of the first 64 patches you should get 4 unique banks in the next version.

I also found another problem in the SVD writing functionality, it shouldn't be affected by which bank the patches are written to but it's a bug nevertheless, so I think this will fix your issue as well.

**Comment by sagamusix** [comment]
Please check out version 0.15, it should hopefully solve both problems!

**Comment by sagamusix** [comment]
To be clear, you will have to start with a fresh JD08Backup.svd file after this fix, taking the one previously modified by JDTools cannot fix the issue.

**Comment by aleks19841** [comment]
0.15 is working as expected.
the "combined" SVD with multiple converted BIN banks loads fine on JD-08
Also SVD2BIN conversion works like a charm.
Part of my confusion was that it looks like there's no way to name presets on JD-08, so after SVD2BIN conversion the banks loaded to JD-800 VST had all the patch names showing "Init Tone", BUT the actual sound is there, it just doesn't have a name !
Great work mate, small donation is on the way.

**Comment by sagamusix** [comment]
Great to hear, and thanks :) It's indeed a bit confusing that patch names are present in JD-08 files despite being impossible to edit on the device.
